feat(circleci): Add revised circle config.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,19 +1,14 @@
-# PHP CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-php/ for more details
-#
 version: 2
 jobs:
   build:
     docker:
-      # specify the version you desire here
-      - image: circleci/php:7.1.5-browsers
+      - image: circleci/php:7.1-node-browsers
+    steps:
+      - checkout
 
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/mysql:9.4
-
+  deploy:
+    docker:
+        - image: circleci/php:7.1-node-browsers #docker:17.11.0-ce-git
     steps:
       - checkout
 
@@ -24,60 +19,60 @@ jobs:
             unzip awscli-bundle.zip
             sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
 
-      # Download and cache dependencies
-#      - restore_cache:
-#          keys:
-#          - v1-dependencies-{{ checksum "composer.json" }}
-#          # fallback to using the latest cache if no exact match is found
-#          - v1-dependencies-
-#
-#      - run: composer install -n --prefer-dist
-#
-#      - save_cache:
-#          paths:
-#            - ./vendor
-#          key: v1-dependencies-{{ checksum "composer.json" }}
+      - run:
+          name: "Log in to AWS ECR"
+          command: yes | eval $(aws ecr get-login --region=eu-west-1 --no-include-email) 2> /dev/null || true # weird exit code, so adding OR true
+
+      - run:
+          name: Build application Docker image
+          command: |
+            docker build -t testwp:$CIRCLE_SHA1 .
+
+      - run:
+          name: Push to ECR
+          command: |
+            docker tag testwp:$CIRCLE_SHA1 $ECR_LOCATION/testwp:latest
+            docker push $ECR_LOCATION/testwp:latest
 
       - deploy:
-          name: Push application Docker image
+          name: Configure task definition
           command: |
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              CLUSTER='test-wp'
-              FAMILY='test-wp'
-              DOCKER_IMAGE='test-wp'
-              TASK='test-wp'
-              SERVICE='test-wp'
-              # Login to AWS
-              aws configure set region $AWS_REGION
-              $(aws ecr get-login)
-              # Tag and push docker image
-              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
-              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
-              # Create task for docker deploy
-              task_template='[
-                {
-                  "name": "%s",
-                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
-                  "essential": true,
-                  "memoryReservation": 1000,
-                  "portMappings": [
-                    {
-                      "containerPort": 80,
-                      "hostPort": 80
-                    }
-                  ],
-                  "environment" : [
-                      { "name" : "NODE_ENV", "value" : "production" }
-                  ]
-                }
-              ]'
-              echo "$task_template"
-              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1)
-              # Register task definition
-              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")
-              # Grab revision # using regular bash and grep
-              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
-              # Deploy revision
-              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
-              return 0
-            fi
+            aws configure set region eu-west-1
+
+            # Create task for docker deploy
+            task_def=$(cat <<EOF
+            [
+              {
+                "name": "test-wp",
+                "image": "${ECR_LOCATION}/testwp:latest",
+                "essential": true,
+                "portMappings": [
+                  {
+                    "containerPort": 80,
+                    "hostPort": 80
+                  }
+                ]
+              }
+            ]
+            EOF
+            )
+
+            # Register task definition
+            json=$(aws ecs register-task-definition \
+              --execution-role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/ecsTaskExecutionRole \
+              --requires-compatibilities "EC2" \
+              --cpu 256 \
+              --memory 0.5gb \
+              --container-definitions "$task_def" \
+              --family "test-wp")
+
+            echo $json
+
+            # Grab revision # using regular bash and grep
+            revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')
+
+            # Deploy revision
+            aws ecs update-service \
+              --cluster "testwp" \
+              --service "test-wp" \
+              --task-definition "test-wp":"$revision"
